## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
 allow_failures:
 - julia: nightly
after_success:
  - julia -e 'cd(Pkg.dir("SpeedTest")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("SpeedTest")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("SpeedTest")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
